name: Changelog and Release
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: install dependencies
        # installs necessary dependencies as semantic-release executes command mentioned in package.json under "scripts" tag
        run: |
          npm install -g typescript jest ncc
          npm install -g semantic-release @semantic-release/github @semantic-release/changelog conventional-changelog-conventionalcommits @semantic-release/commit-analyzer @semantic-release/git
        shell: bash
      - name: release
        run: npx semantic-release